In [2]:
import pandas as pd

import numpy as np

import pyfpgrowth

In [3]:
df = pd.read_csv('www.csv', sep='\t')

In [4]:
print ( df.shape )
print ( df. head () )

(9999, 502)
    UserId                       Query horse http photos in  a up the company  \
0  2304236    washington state lottery     f    f      f  f  f  f   f       f
1  7832793  jc justin been throwing up     f    f      f  f  f  t   f       f
2  9167300        terrace at greenhill     f    f      f  f  f  f   f       f
3    55733           vegas sports line     f    f      f  f  f  f   f       f
4  2686572           the disabled list     f    f      f  f  f  f   t       f

   ... houston why yahoo louis tn maine test local tennessee santa
0  ...       f   f     f     f  f     f    f     f         f     f
1  ...       f   f     f     f  f     f    f     f         f     f
2  ...       f   f     f     f  f     f    f     f         f     f
3  ...       f   f     f     f  f     f    f     f         f     f
4  ...       f   f     f     f  f     f    f     f         f     f

[5 rows x 502 columns]

In [5]:
df.dropna()

,UserId,Query,horse,http,photos,in,a,up,the,company,...,houston,why,yahoo,louis,tn,maine,test,local,tennessee,santa
0,2304236,washington state lottery,f,f,f,f,f,f,f,f,...,f,f,f,f,f,f,f,f,f,f
1,7832793,jc justin been throwing up,f,f,f,f,f,t,f,f,...,f,f,f,f,f,f,f,f,f,f
2,9167300,terrace at greenhill,f,f,f,f,f,f,f,f,...,f,f,f,f,f,f,f,f,f,f
3,55733,vegas sports line,f,f,f,f,f,f,f,f,...,f,f,f,f,f,f,f,f,f,f
4,2686572,the disabled list,f,f,f,f,f,f,t,f,...,f,f,f,f,f,f,f,f,f,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,2784836,421-b tax abatement for staten island,f,f,f,f,f,f,f,f,...,f,f,f,f,f,f,f,f,f,f
9995,8920677,appollo theatre chicago,f,f,f,f,f,f,f,f,...,f,f,f,f,f,f,f,f,f,f
9996,4139696,ford box trucks,f,f,f,f,f,f,f,f,...,f,f,f,f,f,f,f,f,f,f
9997,728654,apartments for rent,f,f,f,f,f,f,f,f,...,f,f,f,f,f,f,f,f,f,f
9998,412723,prism online casino,f,f,f,f,f,f,f,f,...,f,f,f,f,f,f,f,f,f,f

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9999 entries, 0 to 9998
Columns: 502 entries, UserId to santa
dtypes: int64(1), object(501)
memory usage: 38.3+ MB

In [7]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
9994    False
9995    False
9996    False
9997    False
9998    False
Length: 9999, dtype: bool

In [8]:
df.loc[:, df.isnull().any()]

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[9999 rows x 0 columns]

In [9]:
print('Number of rows before removing duplicates:', len(df))
df = df.drop_duplicates('Query', keep='first')
df.reset_index(drop=True, inplace=True)
print('Number of rows after removing duplicates:', len(df))

Number of rows before removing duplicates: 9999
Number of rows after removing duplicates: 9816

In [10]:
df.count()

UserId       9816
Query        9816
horse        9816
http         9816
photos       9816
             ...
maine        9816
test         9816
local        9816
tennessee    9816
santa        9816
Length: 502, dtype: int64

In [11]:
import pyfpgrowth
# Convert the Query column to a list of lists
associations = df['Query'].apply(lambda x: x.split()).tolist()

In [12]:
num_records = len(associations)

In [13]:
sigma = 100
min_support = sigma / num_records
print(f"Minimum support: {min_support}")
# the function find_frequent_patterns takes SIGMA as second parameter
patterns = pyfpgrowth.find_frequent_patterns(associations, sigma)
patterns

Minimum support: 0.010187449062754686

{('high',): 101,
 ('with',): 104,
 ('my',): 110,
 ('home',): 113,
 ('you',): 117,
 ('i',): 117,
 ('is',): 118,
 ('state',): 123,
 ('what',): 128,
 ('city',): 132,
 ('florida',): 136,
 ('school',): 154,
 ('lyrics',): 175,
 ('how',): 178,
 ('how', 'to'): 130,
 ('new',): 222,
 ('http',): 224,
 ('free',): 225,
 ('on',): 232,
 ('county',): 237,
 ('a',): 340,
 ('to',): 426,
 ('and',): 546,
 ('for',): 553,
 ('in', 'the'): 117,
 ('of', 'the'): 207,
 ('in',): 844,
 ('of',): 955}

In [14]:
# number of frequent itemsets found
num_frequent_itemsets = len(patterns)
# maximum size of frequent itemsets
max_itemset_size = max(len(itemset) for itemset in patterns)
print(f'Number of frequent itemsets: {num_frequent_itemsets}')
print(f'Maximum size of frequent itemsets: {max_itemset_size}')

Number of frequent itemsets: 28
Maximum size of frequent itemsets: 2

In [15]:
support = {key: value / len(df) for key, value in patterns.items()}
support

{('high',): 0.010289323553382234,
 ('with',): 0.010594947025264874,
 ('my',): 0.011206193969030154,
 ('home',): 0.011511817440912795,
 ('you',): 0.011919315403422982,
 ('i',): 0.011919315403422982,
 ('is',): 0.01202118989405053,
 ('state',): 0.012530562347188265,
 ('what',): 0.013039934800325998,
 ('city',): 0.013447432762836185,
 ('florida',): 0.013854930725346373,
 ('school',): 0.015688671556642216,
 ('lyrics',): 0.0178280358598207,
 ('how',): 0.018133659331703342,
 ('how', 'to'): 0.013243683781581092,
 ('new',): 0.022616136919315404,
 ('http',): 0.022819885900570498,
 ('free',): 0.022921760391198046,
 ('on',): 0.023634881825590873,
 ('county',): 0.024144254278728607,
 ('a',): 0.03463732681336593,
 ('to',): 0.04339853300733496,
 ('and',): 0.055623471882640586,
 ('for',): 0.05633659331703342,
 ('in', 'the'): 0.011919315403422982,
 ('of', 'the'): 0.0210880195599022,
 ('in',): 0.08598207008964955,
 ('of',): 0.09729013854930725}

In [16]:
support ={key: value/len(df) for key, value in patterns.items()}

support

{('high',): 0.010289323553382234,
 ('with',): 0.010594947025264874,
 ('my',): 0.011206193969030154,
 ('home',): 0.011511817440912795,
 ('you',): 0.011919315403422982,
 ('i',): 0.011919315403422982,
 ('is',): 0.01202118989405053,
 ('state',): 0.012530562347188265,
 ('what',): 0.013039934800325998,
 ('city',): 0.013447432762836185,
 ('florida',): 0.013854930725346373,
 ('school',): 0.015688671556642216,
 ('lyrics',): 0.0178280358598207,
 ('how',): 0.018133659331703342,
 ('how', 'to'): 0.013243683781581092,
 ('new',): 0.022616136919315404,
 ('http',): 0.022819885900570498,
 ('free',): 0.022921760391198046,
 ('on',): 0.023634881825590873,
 ('county',): 0.024144254278728607,
 ('a',): 0.03463732681336593,
 ('to',): 0.04339853300733496,
 ('and',): 0.055623471882640586,
 ('for',): 0.05633659331703342,
 ('in', 'the'): 0.011919315403422982,
 ('of', 'the'): 0.0210880195599022,
 ('in',): 0.08598207008964955,
 ('of',): 0.09729013854930725}

In [17]:
support_val=[0.001, 0.002, 0.003, 0.004, 0.005, 0.006, 0.007, 0.008,
0.009, 0.01]

for min_support in support_val:
    print(f" Current support_value : {min_support}")
    sigma=min_support *num_records
    patterns=pyfpgrowth.find_frequent_patterns(associations,sigma)

    num_frequent_itemsets=len(patterns)
    max_itemset_size=max(len(itemsets) for itemsets in patterns)

    support={key:value /len(df) for key,value in patterns.items()}
    if 140 <= num_frequent_itemsets <= 160:
     print(f"Chosen min_support value (≈150 itemsets) = {min_support}")
    
    print(f" Number of frequent itemsets {num_frequent_itemsets}")
    print(f"maximum itemset {max_itemset_size}")

 Current support_value : 0.001
 Number of frequent itemsets 2281
maximum itemset 10
 Current support_value : 0.002
 Number of frequent itemsets 484
maximum itemset 6
 Current support_value : 0.003
 Number of frequent itemsets 256
maximum itemset 5
 Current support_value : 0.004
Chosen min_support value (≈150 itemsets) = 0.004
 Number of frequent itemsets 156
maximum itemset 4
 Current support_value : 0.005
 Number of frequent itemsets 93
maximum itemset 3
 Current support_value : 0.006
 Number of frequent itemsets 70
maximum itemset 2
 Current support_value : 0.007
 Number of frequent itemsets 57
maximum itemset 2
 Current support_value : 0.008
 Number of frequent itemsets 46
maximum itemset 2
 Current support_value : 0.009
 Number of frequent itemsets 35
maximum itemset 2
 Current support_value : 0.01
 Number of frequent itemsets 29
maximum itemset 2

In [18]:
associations=[list(set(x)) for x in associations]

In [19]:
min_support=0.004
support_count = min_support * num_records
confidence=0.8


patterns = pyfpgrowth.find_frequent_patterns(associations, support_count)
rules = pyfpgrowth.generate_association_rules(patterns, confidence)
rules

{('estate',): (('real',), 0.9166666666666666),
 ('york',): (('new',), 0.8924731182795699),
 ('sale',): (('for',), 0.8333333333333334),
 ('a', 'how'): (('to',), 0.8163265306122449)}

In [23]:
def confidence(X, Y, patterns, num_records):
    # Support(X ∪ Y) / Support(X)
    support_XY = patterns.get(tuple(sorted(X + Y)), 0)
    support_X = patterns.get(tuple(sorted(X)), 0)
    if support_X == 0:
        return 0
    return support_XY / support_X

# Example: real -> estate
conf_real_to_estate = confidence(['real'], ['estate'], patterns, num_records)
print("Confidence real -> estate:", conf_real_to_estate)

Confidence real -> estate: 0.7857142857142857

In [21]:
#task 5 

min_confidence_range = [0.1, 0.3, 0.5, 0.7, 0.9]
for min_conf in min_confidence_range:
    rules = pyfpgrowth.generate_association_rules(patterns, min_conf)
    num_rules = len(rules)
    print(f"Minimum confidence: {min_conf}")
    print(f"Number of generated rules: {num_rules}")
    print()

Minimum confidence: 0.1
Number of generated rules: 17

Minimum confidence: 0.3
Number of generated rules: 14

Minimum confidence: 0.5
Number of generated rules: 7

Minimum confidence: 0.7
Number of generated rules: 5

Minimum confidence: 0.9
Number of generated rules: 1